name: Build Go binaries

on:
  push:
    # Run on all branches
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Golang Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .

      - name: Test
        run: go test -v .
